# Generated by Django 4.2.7 on 2024-01-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering'), ('MSE', 'Material Science Engineering'), ('AE', 'Aerospace Engineering'), ('ME', 'Mechanical Engineering'), ('CHE', 'Chemical Engineering'), ('IE', 'Industrial Engineering'), ('MS', 'Mathematical Science'), ('P', 'Physics'), ('E', 'Economics')], max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('major', models.CharField(choices=[('CE', 'Computer Engineering'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('MSE', 'Material Science Engineering'), ('AE', 'Aerospace Engineering'), ('ME', 'Mechanical Engineering'), ('CHE', 'Chemical Engineering'), ('IE', 'Industrial Engineering'), ('AM', 'Applied Mathematics'), ('P', 'Physics'), ('E', 'Economics')], max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('is_default', models.BooleanField()),
                ('classes', models.ManyToManyField(to='barnomz_app.classsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('knowledge_rate', models.FloatField()),
                ('teaching_rate', models.FloatField()),
                ('communication_rate', models.FloatField()),
                ('exam_difficulty_rate', models.FloatField()),
                ('number_of_votes', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('unit_count', models.PositiveIntegerField()),
                ('group', models.PositiveIntegerField()),
                ('day_of_week', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('final_exam_date', models.DateTimeField()),
                ('number_of_petitioners', models.PositiveIntegerField()),
                ('number_of_capacity', models.PositiveIntegerField()),
                ('number_of_enrolled', models.PositiveIntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.department')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.classroom')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.professor')),
                ('prerequisite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.course')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='CommentOnProfessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.FloatField()),
                ('knowledge_rate', models.FloatField()),
                ('teaching_rate', models.FloatField()),
                ('communication_rate', models.FloatField()),
                ('exam_difficulty_rate', models.FloatField()),
                ('date', models.DateTimeField()),
                ('is_anonymous', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='course_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.course'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.classroom'),
        ),
    ]
