# Generated by Django 4.2.9 on 2024-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barnomz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='barnomz_app.classsession'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
