# Generated by Django 4.2.7 on 2024-01-23 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barnomz_app', '0002_rename_first_name_professor_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='offered_by',
            new_name='presented_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='final_exam_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('Bsc', 'کارشناسی'), ('Msc', 'کارشناسی-ارشد')], default='Bsc', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='warning',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_exam_date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='full_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='classsession',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.classroom'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barnomz_app.classroom'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.commentonprofessors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barnomz_app.user')),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
