# Generated by Django 4.2.7 on 2024-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barnomz_app', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
